# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ssorgatem/Documents/python/video4fuze/GUI/AboutDiag.ui'
#
# Created: Tue Apr 27 21:24:37 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(413, 539)
        Dialog.setMaximumSize(QtCore.QSize(413, 539))
        Dialog.setCursor(QtCore.Qt.WhatsThisCursor)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/silver.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Appinfo = QtGui.QLabel(Dialog)
        self.Appinfo.setCursor(QtCore.Qt.WhatsThisCursor)
        self.Appinfo.setToolTip("")
        self.Appinfo.setText("TextLabel")
        self.Appinfo.setAlignment(QtCore.Qt.AlignCenter)
        self.Appinfo.setWordWrap(True)
        self.Appinfo.setObjectName("Appinfo")
        self.horizontalLayout.addWidget(self.Appinfo)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.logo = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMaximumSize(QtCore.QSize(35, 52))
        self.logo.setCursor(QtCore.Qt.WhatsThisCursor)
        self.logo.setAutoFillBackground(False)
        self.logo.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/icons/black.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setWordWrap(False)
        self.logo.setObjectName("logo")
        self.gridLayout_2.addWidget(self.logo, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.AboutTabs = QtGui.QTabWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AboutTabs.sizePolicy().hasHeightForWidth())
        self.AboutTabs.setSizePolicy(sizePolicy)
        self.AboutTabs.setCursor(QtCore.Qt.WhatsThisCursor)
        self.AboutTabs.setObjectName("AboutTabs")
        self.ReadmeTab = QtGui.QWidget()
        self.ReadmeTab.setCursor(QtCore.Qt.WhatsThisCursor)
        self.ReadmeTab.setAutoFillBackground(False)
        self.ReadmeTab.setObjectName("ReadmeTab")
        self.gridLayout = QtGui.QGridLayout(self.ReadmeTab)
        self.gridLayout.setObjectName("gridLayout")
        self.ReadmeText = QtGui.QTextBrowser(self.ReadmeTab)
        self.ReadmeText.setProperty("cursor", QtCore.Qt.WhatsThisCursor)
        self.ReadmeText.setObjectName("ReadmeText")
        self.gridLayout.addWidget(self.ReadmeText, 0, 0, 1, 1)
        self.AboutTabs.addTab(self.ReadmeTab, "")
        self.LicenseTab = QtGui.QWidget()
        self.LicenseTab.setObjectName("LicenseTab")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.LicenseTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LicenseText = QtGui.QTextBrowser(self.LicenseTab)
        self.LicenseText.setProperty("cursor", QtCore.Qt.WhatsThisCursor)
        self.LicenseText.setObjectName("LicenseText")
        self.horizontalLayout_3.addWidget(self.LicenseText)
        self.AboutTabs.addTab(self.LicenseTab, "")
        self.verticalLayout.addWidget(self.AboutTabs)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(28, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.okButton = QtGui.QPushButton(Dialog)
        self.okButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_2.addWidget(self.okButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.AboutTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.AboutTabs.setTabText(self.AboutTabs.indexOf(self.ReadmeTab), QtGui.QApplication.translate("Dialog", "Readme", None, QtGui.QApplication.UnicodeUTF8))
        self.AboutTabs.setTabText(self.AboutTabs.indexOf(self.LicenseTab), QtGui.QApplication.translate("Dialog", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("Dialog", "Ok", None, QtGui.QApplication.UnicodeUTF8))

import video4fuze_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

