# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ssorgatem/Documents/python/video4fuze/GUI/MainWindow.ui'
#
# Created: Thu Oct  8 16:29:05 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 630)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 711, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.Video = QtGui.QWidget()
        self.Video.setObjectName("Video")
        self.label = QtGui.QLabel(self.Video)
        self.label.setGeometry(QtCore.QRect(-50, 180, 281, 271))
        self.label.setPixmap(QtGui.QPixmap(":/icons/black.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.AddButton = QtGui.QPushButton(self.Video)
        self.AddButton.setGeometry(QtCore.QRect(30, 30, 131, 25))
        self.AddButton.setMinimumSize(QtCore.QSize(131, 25))
        self.AddButton.setObjectName("AddButton")
        self.RemoveButton = QtGui.QPushButton(self.Video)
        self.RemoveButton.setGeometry(QtCore.QRect(30, 130, 131, 25))
        self.RemoveButton.setMinimumSize(QtCore.QSize(131, 25))
        self.RemoveButton.setObjectName("RemoveButton")
        self.tableWidget = QtGui.QTableWidget(self.Video)
        self.tableWidget.setGeometry(QtCore.QRect(190, 40, 511, 511))
        self.tableWidget.setAcceptDrops(True)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.SelectOutputButton = QtGui.QPushButton(self.Video)
        self.SelectOutputButton.setGeometry(QtCore.QRect(20, 80, 151, 25))
        self.SelectOutputButton.setMinimumSize(QtCore.QSize(131, 25))
        self.SelectOutputButton.setObjectName("SelectOutputButton")
        self.ConvertButton = QtGui.QPushButton(self.Video)
        self.ConvertButton.setGeometry(QtCore.QRect(30, 480, 131, 41))
        self.ConvertButton.setMinimumSize(QtCore.QSize(131, 25))
        self.ConvertButton.setObjectName("ConvertButton")
        self.line = QtGui.QFrame(self.Video)
        self.line.setGeometry(QtCore.QRect(0, 10, 641, 31))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtGui.QLabel(self.Video)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 621, 31))
        self.label_4.setFrameShadow(QtGui.QFrame.Raised)
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.Video, "")
        self.Image = QtGui.QWidget()
        self.Image.setObjectName("Image")
        self.label_2 = QtGui.QLabel(self.Image)
        self.label_2.setGeometry(QtCore.QRect(-50, 180, 281, 271))
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/red.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.AddButton_2 = QtGui.QPushButton(self.Image)
        self.AddButton_2.setGeometry(QtCore.QRect(30, 30, 131, 25))
        self.AddButton_2.setMinimumSize(QtCore.QSize(131, 25))
        self.AddButton_2.setObjectName("AddButton_2")
        self.RemoveButton_2 = QtGui.QPushButton(self.Image)
        self.RemoveButton_2.setGeometry(QtCore.QRect(30, 130, 131, 25))
        self.RemoveButton_2.setMinimumSize(QtCore.QSize(131, 25))
        self.RemoveButton_2.setObjectName("RemoveButton_2")
        self.tableWidget_2 = QtGui.QTableWidget(self.Image)
        self.tableWidget_2.setGeometry(QtCore.QRect(190, 40, 511, 511))
        self.tableWidget_2.setAcceptDrops(True)
        self.tableWidget_2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableWidget_2.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_2.setIconSize(QtCore.QSize(40, 40))
        self.tableWidget_2.setShowGrid(False)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.SelectOutputButton_2 = QtGui.QPushButton(self.Image)
        self.SelectOutputButton_2.setGeometry(QtCore.QRect(20, 80, 151, 25))
        self.SelectOutputButton_2.setMinimumSize(QtCore.QSize(131, 25))
        self.SelectOutputButton_2.setObjectName("SelectOutputButton_2")
        self.ConvertButton_2 = QtGui.QPushButton(self.Image)
        self.ConvertButton_2.setGeometry(QtCore.QRect(30, 480, 131, 41))
        self.ConvertButton_2.setMinimumSize(QtCore.QSize(131, 25))
        self.ConvertButton_2.setObjectName("ConvertButton_2")
        self.line_2 = QtGui.QFrame(self.Image)
        self.line_2.setGeometry(QtCore.QRect(0, 10, 641, 31))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtGui.QLabel(self.Image)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 621, 31))
        self.label_5.setFrameShadow(QtGui.QFrame.Raised)
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.Image, "")
        self.Playlists = QtGui.QWidget()
        self.Playlists.setObjectName("Playlists")
        self.SavePlaylist = QtGui.QPushButton(self.Playlists)
        self.SavePlaylist.setGeometry(QtCore.QRect(30, 480, 131, 41))
        self.SavePlaylist.setMinimumSize(QtCore.QSize(131, 25))
        self.SavePlaylist.setObjectName("SavePlaylist")
        self.SongsFromSD = QtGui.QPushButton(self.Playlists)
        self.SongsFromSD.setGeometry(QtCore.QRect(10, 100, 171, 31))
        self.SongsFromSD.setMinimumSize(QtCore.QSize(131, 25))
        self.SongsFromSD.setObjectName("SongsFromSD")
        self.RemoveButton_3 = QtGui.QPushButton(self.Playlists)
        self.RemoveButton_3.setGeometry(QtCore.QRect(30, 140, 131, 25))
        self.RemoveButton_3.setMinimumSize(QtCore.QSize(131, 25))
        self.RemoveButton_3.setObjectName("RemoveButton_3")
        self.SongsFromFuze = QtGui.QPushButton(self.Playlists)
        self.SongsFromFuze.setGeometry(QtCore.QRect(10, 60, 171, 31))
        self.SongsFromFuze.setMinimumSize(QtCore.QSize(131, 25))
        self.SongsFromFuze.setObjectName("SongsFromFuze")
        self.label_3 = QtGui.QLabel(self.Playlists)
        self.label_3.setGeometry(QtCore.QRect(-50, 180, 281, 271))
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/silver.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.playlistWidget = QtGui.QTableWidget(self.Playlists)
        self.playlistWidget.setGeometry(QtCore.QRect(190, 61, 511, 491))
        self.playlistWidget.setAutoFillBackground(True)
        self.playlistWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.playlistWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.playlistWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.playlistWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.playlistWidget.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.playlistWidget.setAlternatingRowColors(True)
        self.playlistWidget.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.playlistWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.playlistWidget.setIconSize(QtCore.QSize(40, 40))
        self.playlistWidget.setObjectName("playlistWidget")
        self.playlistWidget.setColumnCount(5)
        self.playlistWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.playlistWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.playlistWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.playlistWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.playlistWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.playlistWidget.setHorizontalHeaderItem(4, item)
        self.label_6 = QtGui.QLabel(self.Playlists)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 621, 31))
        self.label_6.setFrameShadow(QtGui.QFrame.Raised)
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.line_3 = QtGui.QFrame(self.Playlists)
        self.line_3.setGeometry(QtCore.QRect(0, 10, 641, 31))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.OpenPlaylist = QtGui.QPushButton(self.Playlists)
        self.OpenPlaylist.setGeometry(QtCore.QRect(30, 30, 131, 25))
        self.OpenPlaylist.setMinimumSize(QtCore.QSize(131, 25))
        self.OpenPlaylist.setObjectName("OpenPlaylist")
        self.UpButton = QtGui.QToolButton(self.Playlists)
        self.UpButton.setGeometry(QtCore.QRect(330, 30, 81, 31))
        self.UpButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.UpButton.setAutoRaise(False)
        self.UpButton.setArrowType(QtCore.Qt.UpArrow)
        self.UpButton.setObjectName("UpButton")
        self.DownButton = QtGui.QToolButton(self.Playlists)
        self.DownButton.setGeometry(QtCore.QRect(470, 30, 91, 31))
        self.DownButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.DownButton.setAutoRaise(False)
        self.DownButton.setArrowType(QtCore.Qt.DownArrow)
        self.DownButton.setObjectName("DownButton")
        self.tabWidget.addTab(self.Playlists, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 722, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAdvanced = QtGui.QMenu(self.menuBar)
        self.menuAdvanced.setObjectName("menuAdvanced")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAdd_file = QtGui.QAction(MainWindow)
        self.actionAdd_file.setObjectName("actionAdd_file")
        self.actionAbout_video4fuze = QtGui.QAction(MainWindow)
        self.actionAbout_video4fuze.setObjectName("actionAbout_video4fuze")
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionRemove_selected_files = QtGui.QAction(MainWindow)
        self.actionRemove_selected_files.setShortcut("Del")
        self.actionRemove_selected_files.setObjectName("actionRemove_selected_files")
        self.actionSelect_output_folder = QtGui.QAction(MainWindow)
        self.actionSelect_output_folder.setObjectName("actionSelect_output_folder")
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuFile.addAction(self.actionAdd_file)
        self.menuFile.addAction(self.actionRemove_selected_files)
        self.menuFile.addAction(self.actionSelect_output_folder)
        self.menuHelp.addAction(self.actionAbout_video4fuze)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuAdvanced.addAction(self.actionPreferences)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAdvanced.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "video4fuze 0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.AddButton.setText(QtGui.QApplication.translate("MainWindow", "Add files...", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveButton.setText(QtGui.QApplication.translate("MainWindow", "Remove files", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Input files", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectOutputButton.setText(QtGui.QApplication.translate("MainWindow", "Select output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.ConvertButton.setText(QtGui.QApplication.translate("MainWindow", "Convert!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Video converter", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Video), QtGui.QApplication.translate("MainWindow", "Video", None, QtGui.QApplication.UnicodeUTF8))
        self.AddButton_2.setText(QtGui.QApplication.translate("MainWindow", "Add images...", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveButton_2.setText(QtGui.QApplication.translate("MainWindow", "Remove files", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Input files", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectOutputButton_2.setText(QtGui.QApplication.translate("MainWindow", "Select output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.ConvertButton_2.setText(QtGui.QApplication.translate("MainWindow", "Convert!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Image converter", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Image), QtGui.QApplication.translate("MainWindow", "Photos", None, QtGui.QApplication.UnicodeUTF8))
        self.SavePlaylist.setText(QtGui.QApplication.translate("MainWindow", "Save playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.SongsFromSD.setText(QtGui.QApplication.translate("MainWindow", "Fuze\'s µSD slot", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveButton_3.setText(QtGui.QApplication.translate("MainWindow", "Remove songs", None, QtGui.QApplication.UnicodeUTF8))
        self.SongsFromFuze.setText(QtGui.QApplication.translate("MainWindow", "Fuze\'s internal storage", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistWidget.setSortingEnabled(True)
        self.playlistWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Cover", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Album", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Playlist editor: Add songs from:", None, QtGui.QApplication.UnicodeUTF8))
        self.OpenPlaylist.setText(QtGui.QApplication.translate("MainWindow", "Open playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.UpButton.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.DownButton.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Playlists), QtGui.QApplication.translate("MainWindow", "Playlists", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdvanced.setTitle(QtGui.QApplication.translate("MainWindow", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_file.setText(QtGui.QApplication.translate("MainWindow", "Add files...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_video4fuze.setText(QtGui.QApplication.translate("MainWindow", "About video4fuze", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_selected_files.setText(QtGui.QApplication.translate("MainWindow", "Remove selected files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_output_folder.setText(QtGui.QApplication.translate("MainWindow", "Select output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))

import video4fuze_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

