# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ssorgatem/Documents/python/video4fuze/GUI/Preferences.ui'
#
# Created: Fri Mar 12 21:09:25 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(493, 529)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PreferencesDialog.setWindowIcon(icon)
        self.layoutWidget = QtGui.QWidget(PreferencesDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 490, 351, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtGui.QSpacerItem(131, 31, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.DefaultsButton = QtGui.QPushButton(self.layoutWidget)
        self.DefaultsButton.setObjectName("DefaultsButton")
        self.hboxlayout.addWidget(self.DefaultsButton)
        self.okButton = QtGui.QPushButton(self.layoutWidget)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        self.cancelButton = QtGui.QPushButton(self.layoutWidget)
        self.cancelButton.setDefault(True)
        self.cancelButton.setFlat(False)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        self.label_3 = QtGui.QLabel(PreferencesDialog)
        self.label_3.setGeometry(QtCore.QRect(50, 20, 391, 41))
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.Pass2Check = QtGui.QCheckBox(PreferencesDialog)
        self.Pass2Check.setGeometry(QtCore.QRect(30, 230, 111, 21))
        self.Pass2Check.setChecked(True)
        self.Pass2Check.setObjectName("Pass2Check")
        self.frame = QtGui.QFrame(PreferencesDialog)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(10, 250, 471, 171))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 401, 16))
        self.label_2.setObjectName("label_2")
        self.mencoderpass2Edit = QtGui.QPlainTextEdit(self.frame)
        self.mencoderpass2Edit.setGeometry(QtCore.QRect(10, 30, 451, 131))
        self.mencoderpass2Edit.setObjectName("mencoderpass2Edit")
        self.frame_2 = QtGui.QFrame(PreferencesDialog)
        self.frame_2.setEnabled(True)
        self.frame_2.setGeometry(QtCore.QRect(10, 60, 471, 171))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.mencoderpass1Edit = QtGui.QPlainTextEdit(self.frame_2)
        self.mencoderpass1Edit.setGeometry(QtCore.QRect(10, 30, 451, 131))
        self.mencoderpass1Edit.setObjectName("mencoderpass1Edit")
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(40, 10, 401, 16))
        self.label.setObjectName("label")
        self.label_4 = QtGui.QLabel(PreferencesDialog)
        self.label_4.setGeometry(QtCore.QRect(30, 430, 261, 41))
        self.label_4.setObjectName("label_4")
        self.Wiline = QtGui.QLineEdit(PreferencesDialog)
        self.Wiline.setGeometry(QtCore.QRect(300, 440, 71, 25))
        self.Wiline.setObjectName("Wiline")
        self.Heline = QtGui.QLineEdit(PreferencesDialog)
        self.Heline.setGeometry(QtCore.QRect(412, 440, 71, 25))
        self.Heline.setObjectName("Heline")
        self.label_5 = QtGui.QLabel(PreferencesDialog)
        self.label_5.setGeometry(QtCore.QRect(370, 436, 41, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(PreferencesDialog)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL("clicked()"), PreferencesDialog.accept)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), PreferencesDialog.reject)
        QtCore.QObject.connect(self.Pass2Check, QtCore.SIGNAL("toggled(bool)"), self.frame.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        PreferencesDialog.setWindowTitle(QtGui.QApplication.translate("PreferencesDialog", "video4fuze preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.DefaultsButton.setText(QtGui.QApplication.translate("PreferencesDialog", "Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("PreferencesDialog", "&OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("PreferencesDialog", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PreferencesDialog", "Caution: Modify these settings only if you really know what you do. You have been warned", None, QtGui.QApplication.UnicodeUTF8))
        self.Pass2Check.setText(QtGui.QApplication.translate("PreferencesDialog", "Two passes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PreferencesDialog", "Mencoder pass 2 command line:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PreferencesDialog", "Mencoder pass 1 command line:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PreferencesDialog", "Converted image size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PreferencesDialog", "x", None, QtGui.QApplication.UnicodeUTF8))

import video4fuze_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PreferencesDialog = QtGui.QDialog()
    ui = Ui_PreferencesDialog()
    ui.setupUi(PreferencesDialog)
    PreferencesDialog.show()
    sys.exit(app.exec_())

